apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ereg-sf
  namespace: team-dialog
  labels:
    team: team-dialog
spec:
  webproxy: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 2048Mi
  accessPolicy:
    outbound:
      external:
        - host: login.salesforce.com
        - host: navdialog.my.salesforce.com
  envFrom:
    - secret: ereg-sf
  filesFrom:
    - secret: ereg-sf
  kafka:
    pool: nav-prod # enum of nav-dev, nav-prod
  env:
    - name: KAFKA_BROKERS_ON_PREM
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00148.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443,SASL_SSL://a01apvl00150.adeo.no:8443
    - name: KAFKA_CLIENTID
      value: ereg-sf
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC
      value: public-ereg-cache-org-json
    - name: KAFKA_TOPIC_TOMBSTONES
      value: public-ereg-cache-org-tombstones
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: SF_INSTANCE
      value: PRODUCTION
    - name: SF_VERSION
      value: 'v48.0'
    - name: SF_TOKENHOST
      value: 'https://login.salesforce.com'
    - name: VAULT_INSTANCE
      value: GCP
    - name: KAFKA_USER # When fetching on-prem srv password from gcp secret
      value: srveregsf